version: "3.8"

services:
  web:
    build: ./
    image: django
    restart: always
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
  bot:
    build: ./
    image: bot
    restart: always
    command: >
      bash -c "cd bot && python main.py"
    env_file:
      - .env
    volumes:
      - .:/app